### PR TITLE
get rid of ugly string concatenation and add sassy template strings e…

### PR DESCRIPTION
**Pull request by shyamlohar**
…verywhereeeee

### CODE REVIEW

**Comment by out386** [comment]
Suggestions:
1) Keep the space between function names and the parameter list, to maintain current style
2) Use templates only for the strings that are currently concatenated, also to not affect current code style too much

**Comment by out386** [comment]
No, that last commit doesn't fix spaces. Get me back the spaces between the function names and the parameters. I want my lovely spaces.

**Comment by out386** [comment]
Merged

**Comment by shyamlohar** [comment]
me peru >.<

**Comment by out386** [comment]
You pru

**Pull request closed without merging**
